image: Visual Studio 2017

environment:
  COVERALLS_REPO_TOKEN:
    secure: E4QGOzsFKIG9JaF8MwZdI7gZct7pJ1eekTiKeTmOJIs71+THZNrrfc0l/ORxoyB/

configuration:
  - Debug
  - Release
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
before_build:
- cmd: .\nuget.exe restore
build:
  project: MyPass.sln
  verbosity: normal
artifacts:
  - path: MyPass.Console\bin\Release\netcoreapp2.1
