environment:
  build_version: 6.5.3
  COVERALLS_REPO_TOKEN:
    secure: E4QGOzsFKIG9JaF8MwZdI7gZct7pJ1eekTiKeTmOJIs71+THZNrrfc0l/ORxoyB/
image: Visual Studio 2022
configuration:
  - Debug
  - Release
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v6.3.1/nuget.exe
before_build:
- cmd: .\nuget.exe restore MyPass\MyPass.sln
build:
  project: MyPass.sln
  verbosity: normal
artifacts:
  - path: MyPass.Console\bin\Release