image: Visual Studio 2017

environment:
  COVERALLS_REPO_TOKEN:
    secure: E4QGOzsFKIG9JaF8MwZdI7gZct7pJ1eekTiKeTmOJIs71+THZNrrfc0l/ORxoyB/
before_build:
- nuget restore
build:
  project: MyPass.sln
  verbosity: minimal
after_test:
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]* -[MyPass.Tests]*" -target:"packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:"/domain:single MyPass.Tests/bin/debug/MyPass.Tests.dll" -output:coverage.xml
  - packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml
